# Generated by Django 4.2.2 on 2024-06-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.TextField(default=None)),
                ('log_type', models.TextField(default=None)),
                ('source', models.TextField(default=None)),
                ('message', models.TextField(default=None)),
                ('user_id', models.TextField(default=None)),
                ('session_id', models.TextField(default=None)),
                ('ip_address', models.TextField(default=None)),
                ('request_method', models.TextField(default=None)),
                ('request_path', models.TextField(default=None)),
                ('response_status', models.TextField(default=None)),
                ('data', models.TextField(default=None)),
                ('error_type', models.TextField(default=None)),
                ('error_message', models.TextField(default=None)),
                ('stack_tace', models.TextField(default=None)),
                ('execution_time', models.FloatField(default=0.0)),
            ],
        ),
    ]
