# Generated by Django 4.2.2 on 2024-06-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applogs',
            name='stack_tace',
        ),
        migrations.AddField(
            model_name='applogs',
            name='level',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='applogs',
            name='stack_trace',
            field=models.TextField(default=None),
        ),
    ]
