# Generated by Django 4.2.2 on 2024-06-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_applogs_data_alter_applogs_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
