# Generated by Django 4.2.13 on 2024-06-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_applogs_stack_trace_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
