# Generated by Django 4.2.13 on 2024-06-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_categories_delete_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeexclusion',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
