# Generated by Django 4.2.13 on 2024-06-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_routeexclusion_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeexclusion',
            name='required_token',
            field=models.BooleanField(default=False),
        ),
    ]
