# Generated by Django 4.2.2 on 2025-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_indexdataset_remove_dataset_json_data_dataset_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexdataset',
            name='index',
        ),
        migrations.AddField(
            model_name='indexdataset',
            name='remarks',
            field=models.TextField(default='No Remark'),
        ),
    ]
