# Generated by Django 4.2.2 on 2025-04-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_indexdataset_index_indexdataset_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_info', models.TextField(default=None, null=True)),
            ],
        ),
    ]
