# Generated by Django 4.2.2 on 2025-04-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_testjson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestJson',
            new_name='JsonDataset',
        ),
        migrations.RenameField(
            model_name='jsondataset',
            old_name='json_info',
            new_name='sequential_ecg',
        ),
    ]
