# Generated by Django 4.2.2 on 2025-04-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_dataset_delete_indexdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondataset',
            name='remarks',
            field=models.TextField(default='No Disease'),
        ),
    ]
