# Generated by Django 4.2.2 on 2025-04-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cardiologist_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiologist',
            name='e_signature',
            field=models.FileField(default=None, null=True, upload_to='cardiologist_signature'),
        ),
    ]
