# Generated by Django 4.2.2 on 2025-04-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_prediction_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_trained_state', models.DateField(default=None)),
                ('accuracy', models.TextField(default=None)),
                ('precision', models.TextField(default=None)),
                ('recall', models.TextField(default=None)),
                ('f1_score', models.TextField(default=None)),
                ('json_info', models.TextField(default=None, null=True)),
            ],
        ),
    ]
